INFO - 26/11/2024 10:14:22 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 10:14:22 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 10:27:31 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 10:27:32 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 10:48:39 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 10:48:39 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 12:59:06 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 26/11/2024 12:59:07 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 12:59:08 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 12:59:08 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:01:41 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:01:41 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:01:42 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:01:42 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 13:02:40 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb7aaf6e350>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 13:02:40 : ELASTIC 3 : [5] Something unexpected happened while reading : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb7aaf7ed10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:207)
ERROR - 26/11/2024 13:02:41 : ELASTIC 3 : [5] Something unexpected happened while reading : ApiError(503, 'search_phase_execution_exception', None) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:207)
INFO - 26/11/2024 13:02:43 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:02:43 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:04:04 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:04:04 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:04:06 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:04:06 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:39:10 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:39:10 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:41:39 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:41:39 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 13:54:25 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 13:54:25 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 14:58:07 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1f38bd7890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
INFO - 26/11/2024 15:15:21 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:15:21 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:17:50 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:17:50 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:18:53 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:18:53 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:19:09 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444052550>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444232e10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444052c10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44421bdd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4441dbe10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44421be90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44418e050>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44404bb10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44267df90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44420c050>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4441c2f90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444214b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444049690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444195390>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb442676a50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4441d9f10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44267f810>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb442636310>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb444217ed0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425eb990>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425e8150>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425cbb90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb442619c10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425a7cd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44259c9d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44259e690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb442964b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4429584d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425b9950>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb442635790>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44264ca10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4425bbfd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb4426357d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44264fd50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 26/11/2024 15:19:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb44264f410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
INFO - 26/11/2024 15:19:23 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:19:23 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:19:27 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:19:27 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:19:47 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6530f10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6511690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6530410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd64f8790>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66b6090>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd64f8990>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66680d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6532550>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3fae1d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6673250>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66a7890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66f2ad0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6528d90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd666bfd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9d890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6662150>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66cead0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f66750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f814d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f1fc10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f1c1d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f07f10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f3a410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd59d4290>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd58fac50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd5961290>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd58f9b90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd592af50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd58fa490>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f17c90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd58f8710>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f1d850>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f1df90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f81b90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f3b690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9e210>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f3b310>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66cfed0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66d74d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66bed90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66e9a90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd65307d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66c6750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66725d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f1ce50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66eafd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd64f8b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f64ad0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd64f8690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9c8d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9dfd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd654d010>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6513d90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9e510>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9df50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f66ad0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd66cf1d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9f8d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6668e10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd6693950>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f647d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f9de10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:19:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f3bfd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
ERROR - 26/11/2024 15:20:00 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3fd3f677d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:235)
INFO - 26/11/2024 15:20:02 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:20:02 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:21:18 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:21:18 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:22:10 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:22:10 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:23:09 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:23:09 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:24:02 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:24:02 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:25:17 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:25:17 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:26:01 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:26:01 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:27:47 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:27:47 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:29:49 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:29:49 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:31:05 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:31:05 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:31:31 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1d9f1c4210>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
INFO - 26/11/2024 15:31:43 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:31:43 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:33:24 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:33:24 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:36:08 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f05b5696d50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 15:36:08 : ELASTIC 3 : [5] Something unexpected happened while reading : list indices must be integers or slices, not str - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:216)
INFO - 26/11/2024 15:36:17 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:36:17 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:41:55 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:41:55 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:42:27 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb92fdede10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 15:42:27 : ELASTIC 3 : [5] Something unexpected happened while reading : list indices must be integers or slices, not str - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:209)
INFO - 26/11/2024 15:42:39 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:42:39 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 15:43:46 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:43:46 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 15:44:20 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f0fd65e37d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 15:44:20 : ELASTIC 3 : [5] Something unexpected happened while reading : list indices must be integers or slices, not str - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:209)
INFO - 26/11/2024 15:44:32 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 15:44:32 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:20:53 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:20:53 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:21:18 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9dbbb70b10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 17:21:18 : ELASTIC 3 : [5] Something unexpected happened while reading : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9dbbb4b8d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:209)
INFO - 26/11/2024 17:21:29 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:21:29 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:24:14 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:24:14 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:25:02 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:25:02 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:25:28 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef47953650>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 17:25:28 : ELASTIC 3 : [5] Something unexpected happened while reading : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4790bc10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:209)
ERROR - 26/11/2024 17:25:30 : ELASTIC 3 : [5] Something unexpected happened while reading : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef47f726d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:209)
INFO - 26/11/2024 17:25:41 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:25:41 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:32:12 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:32:12 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:35:25 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:35:25 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:36:05 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:36:05 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:36:19 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:36:19 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_images': {'sum': {'script': "doc['m_images'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_videos': {'sum': {'script': "doc['m_video'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'script': {'script': "doc['m_content'].value.length() > 5000"}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_content_length': {'avg': {'script': "doc['m_content'].value.length()"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_important_content_length': {'avg': {'script': "doc['m_important_content'].value.length()"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sections': {'avg': {'script': "doc['m_section'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sub_url_count': {'avg': {'script': "doc['m_sub_url'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:36:19 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_clearnet_links': {'sum': {'script': "doc['m_clearnet_links'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
INFO - 26/11/2024 17:38:16 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:38:17 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:39:03 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c13fb90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'unique_urls': {'cardinality': {'field': 'm_url.keyword'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3f98d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'unique_base_urls': {'cardinality': {'field': 'm_base_url.keyword'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c101e90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'match_all': {}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3da510>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_validity_score': {'avg': {'field': 'm_validity_score'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3c6690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'exists': {'field': 'm_important_content'}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c101190>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_images': {'sum': {'script': "doc['m_images'].length"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3b2c50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_videos': {'sum': {'script': "doc['m_video'].length"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3b1b90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'exists': {'field': 'm_meta_description'}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c13f110>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'unique_keywords': {'cardinality': {'field': 'm_keywords.keyword'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c37ec10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'range': {'m_update_date': {'gte': 'now-30d/d'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c3c7bd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'script': {'script': "doc['m_content'].value.length() > 5000"}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c363590>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_content_length': {'avg': {'script': "doc['m_content'].value.length()"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c357d90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_important_content_length': {'avg': {'script': "doc['m_important_content'].value.length()"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c101d50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sections': {'avg': {'script': "doc['m_section'].length"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c34f650>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'term': {'m_content_type.keyword': 'general'}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c326d10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_phone_numbers': {'cardinality': {'field': 'm_phone_numbers.keyword'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c317490>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'exists': {'field': 'm_sub_url'}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c315f10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'unique_hashes': {'cardinality': {'field': 'm_hash.keyword'}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c4fb090>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sub_url_count': {'avg': {'script': "doc['m_sub_url'].length"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c4eb490>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:03 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_clearnet_links': {'sum': {'script': "doc['m_clearnet_links'].length"}}}}} : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f767c316150>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
INFO - 26/11/2024 17:39:13 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:39:13 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_images': {'sum': {'script': "doc['m_images'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_videos': {'sum': {'script': "doc['m_video'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'query': {'script': {'script': "doc['m_content'].value.length() > 5000"}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_content_length': {'avg': {'script': "doc['m_content'].value.length()"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_important_content_length': {'avg': {'script': "doc['m_important_content'].value.length()"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sections': {'avg': {'script': "doc['m_section'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'avg_sub_url_count': {'avg': {'script': "doc['m_sub_url'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
ERROR - 26/11/2024 17:39:41 : ELASTIC 3 : Failed to execute query : {'m_document': 'generic_model', 'm_filter': {'size': 0, 'aggs': {'total_clearnet_links': {'sum': {'script': "doc['m_clearnet_links'].length"}}}}} : BadRequestError(400, 'search_phase_execution_exception', 'runtime error') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:219)
INFO - 26/11/2024 17:40:36 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:40:36 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:43:25 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:43:25 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:43:36 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:43:36 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:44:51 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:44:51 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:45:29 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:45:29 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:47:22 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:47:22 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:50:13 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:50:14 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:51:51 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fea20c34350>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
INFO - 26/11/2024 17:52:02 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:52:02 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 26/11/2024 17:53:26 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f4e53377950>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
INFO - 26/11/2024 17:53:37 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:53:37 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:54:26 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:54:26 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:54:30 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:54:30 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:58:18 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:58:18 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 17:58:26 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 17:58:26 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:02:06 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:02:06 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:02:16 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:02:16 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:05:41 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:05:41 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:05:44 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:05:44 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:06:21 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:06:21 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:07:12 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:07:12 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:08:56 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:08:56 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:09:43 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:09:43 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:17:56 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:17:56 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:18:09 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:18:09 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:19:44 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:19:44 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:20:40 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:20:40 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:22:04 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:22:04 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:22:10 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:22:10 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:22:57 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:22:57 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:22:58 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:22:59 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:24:04 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:24:04 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:24:06 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:24:06 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:25:45 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:25:45 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:25:50 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:25:50 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:30:31 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:30:31 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 26/11/2024 18:30:36 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 26/11/2024 18:30:36 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
